# Build Stage
FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
COPY client/package*.json ./client/
WORKDIR /app/client
RUN npm install
COPY client ./
# Capture build-time env vars
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# Serve Stage
FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/client/dist ./dist
EXPOSE 5173
# Start usage of shell to allow variable expansion
CMD ["/bin/sh", "-c", "serve -s dist -l ${PORT:-5173}"]
