# Build Stage
FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
COPY client/package*.json ./client/
WORKDIR /app/client
RUN npm install
COPY client ./
RUN npm run build

# Serve Stage
FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/client/dist ./dist
EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
